### ISSUE TITLE
炫彩皮肤 API 以及符文相关功能

### ISSUE THREAD

**Issue by EmiliatanMajiTennshi** [Hanxven/LeagueAkari#1]
我有几个炫彩没有原皮肤, 想通过api直接选择, 但是没找到

**Comment by Hanxven** [comment]
很抱歉，暂时不知道。

**Comment by AiUWei** [comment]
能加入英雄出装推荐功能吗？非常喜欢这个软件

**Comment by Hanxven** [comment]
> 能加入英雄出装推荐功能吗？非常喜欢这个软件

此功能可能要依赖外部数据源（如 OP.GG）。

现在正在开发自动符文相关功能，这个需求优先级较高。

如果您对这个项目感兴趣，请尽情提交 PR :)
