### ISSUE TITLE
[Feature Request] 双屏体验优化：记住上次打开窗口位置（主要）

### ISSUE THREAD

**Issue by X012C** [Hanxven/LeagueAkari#100]
1、每次打开界面都会重置到主屏幕中心，希望能够记住上次打开窗口位置（开关）。
2、对局信息排版优化， 对局信息拉满全屏（竖屏）才堪堪看全双方人员信息，然后英雄信息就被挡在下面。方块豆腐信息的UI在横竖屏状态都会存在大量空白，希望能够得到优化。
3、英雄选择信息可以选择整合到对局主框体的下面（开关）。

**Comment by Hanxven** [comment]
暂时没有对应的测试环境，作者只能买得起小屏幕的电脑。日后有钱一定优化大屏体验。

**Comment by X012C** [comment]
> 暂时没有对应的测试环境，作者只能买得起小屏幕的电脑。日后有钱一定优化大屏体验。 

草，被你模板骗了，要是知道你这样回复，我一定措辞拉满。（拂面流泪）

**Comment by Hanxven** [comment]
> > 暂时没有对应的测试环境，作者只能买得起小屏幕的电脑。日后有钱一定优化大屏体验。
> 
> 草，被你模板骗了，要是知道你这样回复，我一定措辞拉满。（拂面流泪）

偶尔也要非正式一点，虽然我大部分时间都假装像个人。
