### ISSUE TITLE
[Feature Request] 期望增加胜率队/小代预警功能

### ISSUE THREAD

**Issue by Kaze-maru** [Hanxven/LeagueAkari#102]
期望增加胜率队/小代预警功能，可以实现加载界面时，获取对面某人胜率高于自定义某值（例80%）进行预警提示，类似悠米助手的功能，便于玩家能在游戏开始时决定这把认真打or三分钟重开。

**Comment by Kaze-maru** [comment]
> 期望增加胜率队/小代预警功能，可以实现加载界面时，获取对面某人胜率高于自定义某值（例80%）进行预警提示，类似悠米助手的功能，便于玩家能在游戏开始时决定这把认真打or三分钟重开。
-----------------------------
胜率建议从近20场抓取

**Comment by Zxcx1** [comment]
有这个功能，我记得胜率队直接会显示胜率队.

**Comment by Hanxven** [comment]
该相关页面将重构。敬请期待 1.2.5 正式版的对局分析页面。

**Comment by Kaze-maru** [comment]
> 有这个功能，我记得胜率队直接会显示胜率队.

我的意思是会有弹窗之类的显著提醒，一般加载界面较少会特意的去翻看对局分析~
