### ISSUE TITLE
[Feature Request] 可否添加一下界面ui换肤和字体的功能，有时候看起来感觉很费劲

### ISSUE THREAD

**Issue by linux-dxr** [Hanxven/LeagueAkari#106]
灵感总是来自于四面八方，欢迎提出您的建议。但是在提出之前，请尽量遵守以下规则：

1. 是否已经有人提出过类似建议了？请先搜索一下。

2. 避免无意义客套话和无关修饰词句。

    **错误示范1**：作者辛苦了，希望能够增加一个新的 xxx 功能，谢谢。
    **错误示范2**：(●'◡'●)(❁´◡`❁)╰(*°▽°*)╯，希望能够增加一个新的 xxx 功能，阿里嘎多~~OvO。
    **正确示范**：希望增加一个新的功能，可以实现 xxx。

3. 避免提出宝宝需求。

    **错误示范1**：可以出一个解压教程吗？
    **错误示范2**：可以出一个使用教程吗？

4. 每一个 Issue 请仅包含单个建议，避免一次性提出多个建议。

5. 如果有现成的解决方案，可以提供链接或参考。

感谢您的理解和配合。

**Comment by BakaFT** [comment]
**换肤**二字十分宽泛，但实际情况是即使是**换色**也需要一套设计合理的颜色搭配，并且需要考虑到有的组件可能使用硬编码值，适配工作不会有那么轻松，如果有兴趣做出贡献，参考https://www.naiveui.com/zh-CN/light/docs/customize-theme

换字体这事情相比之下简单得多

**Comment by Hanxven** [comment]
近几个版本暂不考虑实现。
