### ISSUE TITLE
[Feature Request] 打开的标签页关闭后建议打开它右边的标签页

### ISSUE THREAD

**Issue by ruinmi** [Hanxven/LeagueAkari#115]
![image](https://github.com/user-attachments/assets/a8a2b8b1-4001-4f2d-8f63-6584a9de47cc)

浏览器这种的标签页关闭也是这样的逻辑，所以感觉更适应一点。

目前是打开的标签页关闭后，打开的标签页是它左边的

**Comment by Hanxven** [comment]
已实装。
