### ISSUE TITLE
[Bug] 今天使用后打了一把无限火力，被封号1小时了，希望大家注意。

### ISSUE THREAD

**Issue by AemonCao** [Hanxven/LeagueAkari#116]
RT，版本是：1.2.6-fix.2-win。

**Comment by Hanxven** [comment]
请仔细阅读 [`README.md`](https://github.com/Hanxven/LeagueAkari?tab=readme-ov-file#6-%E5%85%8D%E8%B4%A3%E5%A3%B0%E6%98%8E) 的免责声明部分。
