### ISSUE TITLE
[Bug] 战绩/对局页面无法对排位/大乱斗等分类

### ISSUE THREAD

**Issue by HengCao1** [Hanxven/LeagueAkari#118]
1. 1.2.6 fix1，日服14.19， Windows 10

2. 只记得此版本会出现该问题

3. 一定会复现

4. 在战绩页面，即使选择了Ranked Solo/Duo，战绩中仍会出现非排位战绩。对局页面同理，也会出现队友的非排位战绩。
![对局页面](https://github.com/user-attachments/assets/84ee09a3-992b-4cbb-a9ab-0c6e8dc1587e)
![战绩查询页面](https://github.com/user-attachments/assets/a8324cf9-f47e-4abd-aaab-95be136e8711)

**Comment by Hanxven** [comment]
战绩页面展示队列模式下拉框为 BUG (正常情况下应该隐藏)。因为筛选战绩依赖于 SGP API，目前并未支持日服的 SGP 服务器。

提供一个**可能会**可行的方案：

1. 打开设置 => 调试 => 存储 => 应用目录
2. 编辑其下 `AkariConfig/external-data-source/mh-sgp-servers_v6.json`
3. 在 `servers` 选项下，添加以下新内容：
```json
"JP1": {
   "name": "JP1",
   "matchHistory": "https://apne1-red.pp.sgp.pvp.net",
   "common": "https://jp-red.lol.sgp.pvp.net"
}
```
4. 重新启动软件。
