### ISSUE TITLE
个人主页战绩无法提取和对战信息战绩其他玩家信息无法显示

### ISSUE THREAD

**Issue by DspWilliam** [Hanxven/LeagueAkari#12]
您好，我是win10操作系统，前两天用起来没什么问题，从昨天开始，突然在个人战绩显示界面一直报500和503错误，今天使用新版本的之后，这个问题也没有解决。打排位的时候，对局信息只显示双方名字，战绩都不显示，向您反馈一下。

**Comment by Hanxven** [comment]
如果是艾欧尼亚大区，那么这个暂时没法解决。这个大区在晚上的时候似乎很多接口会请求失败。

DspWilliam ***@***.***> 于 2024年3月25日周一 22:03写道：
