### ISSUE TITLE
[Feature Request] 希望能增加对局开始自动发送文本

### ISSUE THREAD

**Issue by Kilomiyaa** [Hanxven/LeagueAkari#121]
#### 只想安静的打游戏...
想要开局自动静音所有人和自己。
虽然自定义发送文本可以实现，但是还是感觉像自动接受对局一样更方便一些，有些时候会忘记。
希望能在现有的自定义发送文本的基础上添加开局自动发送，作者辛苦了。
![ 2024-10-12 190748.png](https://s2.loli.net/2024/10/12/l7GSRDVf5vtk8Lg.png)

**Comment by Hanxven** [comment]
无法掌握自动发送的时机。

在新版本 (v1.3.0) 中，可自由设置多个发送文案以及对应的快捷键，这也许有用。
