### ISSUE TITLE
[Bug] 对局完成后lol客户端会消失

### ISSUE THREAD

**Issue by sbcarp** [Hanxven/LeagueAkari#125]
为了知道 BUG 的源头，请您尽可能描述：

1. 出现问题的版本。
1.26-fix.2
2. 之前版本是否出现该问题？这将会帮助缩小排查范围。
并未使用过旧版
3. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。
大乱斗对局完成后LOL客户端会消失（或者说不会出现），复现概率大概是40%
有的时候在选英雄的时候也会莫名消失
但如果发现客户端消失后，退出LeagueAkari，客户端则会再次出现，感觉是LeagueAkari阻塞了某个东西

4. 这个问题具体是什么样子的？如果有截图或报错文字会更好。
如上，并未发现报错文字

5. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。
Windows 11 Pro 23H2 英文版，用的是北美的LOL客户端，版本v14.20.625.2220

6. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。
暂无，下次复现的时候我来上传控制台输出

**Comment by sbcarp** [comment]
如果在LOL客户端中把“Close client during game”设置成“never”好像就不会遇到这个问题了，之前是as needed。
不过不知道能不能解决选英雄时偶尔客户端会消失的问题，那个问题遇到的概率很低

**Comment by BakaFT** [comment]
> 但如果发现客户端消失后，退出LeagueAkari，客户端则会再次出现，感觉是LeagueAkari阻塞了某个东西
> 如果在LOL客户端中把“Close client during game”设置成“never”好像就不会遇到这个问题了，之前是as needed

这个问题也许和Akari无关，缺乏绝对的证据能说明是Akari阻塞了UX重启的过程

> 不过不知道能不能解决选英雄时偶尔客户端会消失的问题，那个问题遇到的概率很低

这个可能还是老问题，外部高频调用LeagueClient.exe的HTTP API时，有概率杀死UX
国服这边改用直接使用SGP API后基本无人再反馈

但是Akari对外服的SGP支持并不完整，需要你手动获取SGP服务器地址然后参考 #118 手动添加`NA1`项目
不可靠的猜测(无法确定matchHistory和common是否相同，但是北美服务器建设很早且不存在跨区域问题，应该相同）:
```json
"NA1": {
   "name": "NA1",
   "matchHistory": "https://na-red.lol.sgp.pvp.net",
   "common": "https://na-red.lol.sgp.pvp.net"
}
```

**Comment by sbcarp** [comment]
> 这个问题也许和Akari无关，缺乏绝对的证据能说明是Akari阻塞了UX重启的过程

感觉多少还是有点关系吧，毕竟LOL客户端是在我退出Akari的瞬间恢复正常的，不过我也不清楚怎么样debug这个东西。这东西不解决其实也无所谓，我把客户端设置为一直可见貌似就再也没遇到过了

> 但是Akari对外服的SGP支持并不完整，需要你手动获取SGP服务器地址然后参考 https://github.com/Hanxven/LeagueAkari/issues/118 手动添加NA1项目
不可靠的猜测(无法确定matchHistory和common是否相同，但是北美服务器建设很早且不存在类似太平洋地区的跨区域问题，应该相同

好的谢谢！
