### ISSUE TITLE
[Feature Request] 希望能够在启动LeagueAkari时自动拉起客户端

### ISSUE THREAD

**Issue by SHERfourteen** [Hanxven/LeagueAkari#128]
希望增加一个新的功能，可以实现在启动LegueAkari时自动拉起客户端。
![image](https://github.com/user-attachments/assets/a25b0314-efd5-4ae9-9fb5-903044f0c109)

**Comment by MVPjoker** [comment]
如果可以的话 我也特别希望加上这个功能 很方便

**Comment by good-ideal** [comment]
我也需要

**Comment by Hanxven** [comment]
我会尝试做一个手动启动的版本实验一下。

**Comment by miss17year** [comment]
坐等！

**Comment by The-spotlight** [comment]
再来个开机自启动，启动LeagueAkari时自动拉起客户端，在自动开启匹配，完美。

**Comment by Conliq** [comment]
可以自己写一个bat脚本，点击脚本后，将同时打开wegame与League Akrai
start  ""  "E:\Wegame\wegame.exe" 
start  ""  "D:\Program Files (x86)\League Akari-1.3.2-win\LeagueAkari.exe"

**Comment by SHERfourteen** [comment]
> 可以自己写一个bat脚本，点击脚本后，将同时打开wegame与League Akrai start "" "E:\Wegame\wegame.exe" start "" "D:\Program Files (x86)\League Akari-1.3.2-win\LeagueAkari.exe"

之前确实这样子用了一段时间，多谢指点😘
