### ISSUE TITLE
[Feature Request] 获取战绩信息加入大区信息字段

### ISSUE THREAD

**Issue by comtnt** [Hanxven/LeagueAkari#13]
例如联盟三区【班德尔城、裁决之地、水晶之痕、钢铁烈阳、皮城警备】，这些区合区后能一起匹配，在战绩信息卡片加入具体的大区名称（班德尔城、裁决之地、水晶之痕、钢铁烈阳、皮城警备）

**Comment by Hanxven** [comment]
已纳入考虑中，感谢您的意见。

**Comment by Hanxven** [comment]
@comtnt 我目前在检查的过程中，似乎没有找到辨认大区的方法。

对于一些已经合并的大区，其平台 ID 也只会是一个新的代号（如 "GD100"），推测可能是连接到了同一个服务器。

但在 1.1.4 版本中，仍会尝试标记其大区字段。
