### ISSUE TITLE
[Feature Request] 加油，已有大佬坚持很多年了，可以参考下

### ISSUE THREAD

**Issue by dmarkdmark** [Hanxven/LeagueAkari#132]
灵感总是来自于四面八方，欢迎提出您的建议。但是在提出之前，请尽量遵守以下规则：

1. 是否已经有人提出过类似建议了？请先搜索一下。
只是给建议
2. 避免无意义客套话和无关修饰词句。

    **错误示范1**：作者辛苦了，希望能够增加一个新的 xxx 功能，谢谢。
    **错误示范2**：(●'◡'●)(❁´◡`❁)╰(*°▽°*)╯，希望能够增加一个新的 xxx 功能，阿里嘎多~~OvO。
    **正确示范**：希望增加一个新的功能，可以实现 xxx。

3. 避免提出宝宝需求。

    **错误示范1**：可以出一个解压教程吗？
    **错误示范2**：可以出一个使用教程吗？

4. 每一个 Issue 请仅包含单个建议，避免一次性提出多个建议。

5. 如果有现成的解决方案，可以提供链接或参考。

感谢您的理解和配合。

这位大佬已开发蛮久了，希望超越他
https://github.com/Zzaphkiel/Seraphine

**Comment by Hanxven** [comment]
在本项目的开发过程中，[Seraphine](https://github.com/Zzaphkiel/Seraphine) 的作者提供了很多帮助，在此提出感谢。如果你足够细心，应该可以在本项目的 **`README.md`** 或者源码中找到 [Seraphine](https://github.com/Zzaphkiel/Seraphine) 的痕迹，

本项目仅在于为大家提供一个**免费的**英雄联盟客户端工具集，以及为未来的同类开源项目提供参考，而非超过 xxx 或打败 xxx。

**还请不要提出无关 issue。**

**Comment by dmarkdmark** [comment]
sry
那我关了
