### ISSUE TITLE
[Feature Request] 希望抓取一下英雄技能说明

### ISSUE THREAD

**Issue by X012C** [Hanxven/LeagueAkari#133]
![image](https://github.com/user-attachments/assets/cb5346e8-2ab4-4b2d-ba61-c701287d1f13)
谢谢。

**Comment by Hanxven** [comment]
似乎有点冗余。

**Comment by X012C** [comment]
> 似乎有点冗余。

是说布局吗？合并到QWER的技能点法里面如何？ 像天赋布局那样，鼠标放在上面才弹窗显示。
