### ISSUE TITLE
隐藏战绩嘲讽语文本

### ISSUE THREAD

**Issue by J-EnJay** [Hanxven/LeagueAkari#134]
1.2.3移除的隐藏战绩嘲讽语还挺有意思的，可惜我没找到改动的文件，能否指个路

**Comment by Hanxven** [comment]
可以在 `v1.1.x` 分支 [here](https://github.com/Hanxven/LeagueAkari/blob/legacy-1.1.x/src/renderer/src/utils/sarcasms.ts) 找到。
