### ISSUE TITLE
战绩简报功能和自定义文本要移除吗?

### ISSUE THREAD

**Issue by haoyun1718** [Hanxven/LeagueAkari#138]
你好,下载最新版本发现没有发送战绩简报和自定义文本功能了,是准备移除掉吗?这两个功能我觉得很实用,战绩简报可以清晰看到队友胜率信息,自定义文本可以进游戏 //mute all，想体验新版本的ui布局，但是这两个功能没有在新版本里边，很遗憾

**Comment by Hanxven** [comment]
**并不会移除**，而是考虑对其进行一些功能上的加强。

因为目前的快捷键逻辑还没有搞定，部分涉及到快捷键的功能还只是占位。
