### ISSUE TITLE
[Feature Request] 建议加入召唤师英雄区服排名

### ISSUE THREAD

**Issue by pcccccc** [Hanxven/LeagueAkari#14]
wegame点击部分玩家名，可以在主页带出玩家英雄区服排名，类似于：

“比尔吉沃特第一霞”

希望可以添加这个内容，这样可以更好的在匹配/大乱斗中判断胜率队。

**Comment by Hanxven** [comment]
这个需求有点困难，因为它似乎不是标准 LCU API 能实现的内容。
