### ISSUE TITLE
[Feature Request] 建议添加“最后一秒锁定”功能或者“延迟几秒锁定”功能

### ISSUE THREAD

**Issue by luqijun** [Hanxven/LeagueAkari#142]
排位赛的时候，有时候需要根据阵容灵活选择恰当的英雄。目前“立即锁定”功能，很可能导致没来得及切换英雄；“亮出而不锁定”功能又需要自己手动点一下。若加上“最后一秒锁定”功能，既可以又充足时间切换英雄，又可以防止忘记锁定。

**Comment by Hanxven** [comment]
可以。
