### ISSUE TITLE
[Bug] 无法启动TCLS客户端

### ISSUE THREAD

**Issue by good-ideal** [Hanxven/LeagueAkari#145]
至少提供以下信息：

1. 出现问题的版本。
1.3.1
![image](https://github.com/user-attachments/assets/aef12144-76e8-4a6b-ab0e-9315e688def9)

**Comment by Hanxven** [comment]
看来是没有遇到过的错误，尝试以管理员身份运行试试。

**Comment by good-ideal** [comment]
> 看来是没有遇到过的错误，尝试以管理员身份运行试试。

使用管理员身份运行也是一样的错误，wegame也无法启动
![image](https://github.com/user-attachments/assets/f41f60e7-8055-4a19-90b3-e41cc49cba73)

**Comment by SHERfourteen** [comment]
![image](https://github.com/user-attachments/assets/bcd0910b-cd76-4b94-a68b-5016ca41a201)
相同问题。

**Comment by Hanxven** [comment]
> ![image](https://private-user-images.githubusercontent.com/111401964/393560749-bcd0910b-cd76-4b94-a68b-5016ca41a201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MzYwNDQsIm5iZiI6MTczMzYzNTc0NCwicGF0aCI6Ii8xMTE0MDE5NjQvMzkzNTYwNzQ5LWJjZDA5MTBiLWNkNzYtNGI5NC1hNjhiLTUwMTZjYTQxYTIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQwNTI5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDcxYjAzYzQwZmM0ZTlmNTNiYWNkZTYzNzI2NWQzOWUwZWM5MDU2YzkxOWEyOGQxZDVhNzNhNDIxYTNiYmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ii2tFQLVcfI43hbGZZeh1xB_7BFWJaJBRn9g4XCvL7k) 相同问题。

感谢没有乱码的版本，那我大概知道原因了。之后会更小心地处理空格。

**Comment by Hanxven** [comment]
将在 v1.3.2 修复。
