### ISSUE TITLE
只用一键天赋，封号了，大号三年，小号一小时

### ISSUE THREAD

**Issue by CarryLeeS** [Hanxven/LeagueAkari#149]
只用一键天赋，封号了，大号三年，小号一小时

**Comment by Hanxven** [comment]
6. 免责声明
本软件作为基于 Riot 提供的 League Client Update (LCU) API 开发的辅助工具，由于其设计和实施均未采用侵入性技术手段，理论上不会直接干预或修改游戏数据。然而，需明确指出的是，虽然本软件在原理上并未直接修改游戏内部数据，但在游戏环境的持续更新和演变中 (如未来腾讯可能的反作弊系统或其他保护服务的更新)，无法完全排除由于版本更新导致的兼容性问题或其他意外后果。

特此强调，对于使用本软件可能带来的任何后果，包括但不限于游戏账户的封禁、数据损坏或其他任何形式的游戏体验负面影响，本软件的开发者将不承担任何责任。用户在决定使用本软件时，应充分考虑并自行承担由此产生的所有风险和后果。

本声明旨在全面而详尽地通知用户关于本软件使用的可能风险，以便用户在使用过程中做出充分的风险评估和明智的决策。感谢您的关注，同时敬请遵守相关游戏规则和使用指南，确保一种健康和公平的游戏环境。

**Comment by BakaFT** [comment]
![image](https://github.com/user-attachments/assets/e1ce9a3b-2d30-4303-bc81-bad2acc0eb9d)

🤷

**Comment by CarryLeeS** [comment]
万分抱歉，换肤导致的
