### ISSUE TITLE
[优化] 关于tab切换卡顿的问题

### ISSUE THREAD

**Issue by watchingfun** [Hanxven/LeagueAkari#15]
你可以使用v-show +  v-for 来缓存打开的tab页，这样每次切换就不会重新计算生成dom
然后可以使用[v-lazy-component](https://v-lazy-component.vercel.app/demo) 来解决初始渲染时间过长导致卡顿的问题
然后随便推介这个库，可以很方便做切换过渡动画[@morev/vue-transitions](https://morevm.github.io/vue-transitions/)

我也做了个助手程序，相见恨晚啊，😂

**Comment by Hanxven** [comment]
@watchingfun 感谢您的建议。
