### ISSUE TITLE
[Feature Request] 排位自动选人建议

### ISSUE THREAD

**Issue by MichaelNec** [Hanxven/LeagueAkari#152]
自动选人可以设置多个英雄并且可以设置优先级，但不能设置对应英雄的匹配天赋，建议增加这个设置，可以为多个英雄设置专属的天赋和召唤师技能

**Comment by Hanxven** [comment]
很久之前就想加了，但实现起来并不容易。

**Comment by MichaelNec** [comment]
我不太懂代码啊，是什么原因呢？是因为没有对应的API么，天赋页还是现成的，手动设定一下，跟选英雄一样选了就行，是因为没有对应的API可以调用么，模拟键盘呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hanxven/LeagueAkari"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月10日(星期二) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hanxven/LeagueAkari] [Feature Request] 排位自动选人建议 (Issue #152)





 
很久之前就想加了，但实现起来并不容易。

**Comment by Hanxven** [comment]
如果不懂代码，我不建议发言。
