### ISSUE TITLE
[Feature Request] 双排&多排检测不准确，显示方式改善建议

### ISSUE THREAD

**Issue by DemonBrand** [Hanxven/LeagueAkari#155]
双排和多排检测有一点不准确，同样使用Akari和Seraphine，组队人显示不一样，Seraphine显示出来但是Akari没有显示，同时多排检测的显示方式可以改成以不同颜色背景标注的形式，可以参考Seraphine

**Comment by Hanxven** [comment]
请给出不准确的样例，以复现测试。
