### ISSUE TITLE
建议将OPGG添加到软件界面左侧的工具栏，这样更直观

### ISSUE THREAD

**Issue by DemonBrand** [Hanxven/LeagueAkari#156]
建议将OPGG添加到软件界面左侧的工具栏，这样更直观，参考seraphine
![1](https://github.com/user-attachments/assets/9000f6aa-d7e7-4f7b-819e-12d720d27c6b)

**Comment by Hanxven** [comment]
OPGG 不属于核心功能，不会集成在这里。
