### ISSUE TITLE
[Bug] 大乐斗的情况下，点击接受游戏，进入选人页面，不会应用天赋，换个英雄之后就可以应用天赋了

### ISSUE THREAD

**Issue by Z46I4W5476SJA** [Hanxven/LeagueAkari#160]
搜索了一下  ，好像没有人提过这个问题

第一次使用这个软件，所以不知道之前的版本有没有这个问题
现象：大乐斗点击接受游戏之后，进入选人阶段，这个时候没有自动应用天赋，然后我换个英雄之后，就会自动应用天赋了

[LA_20241212_211605926.log](https://github.com/user-attachments/files/18136207/LA_20241212_211605926.log)

[video_20241214_220406_edit.zip](https://github.com/user-attachments/files/18136208/video_20241214_220406_edit.zip)

**Comment by Hanxven** [comment]
日志和视频已查阅。

这个软件目前为止 (v1.3.2 及以前) 并没有自动应用符文的功能，即使是小窗集成的 OP.GG，也需要**手动**设置符文。

根据视频内容，它更像是客户端内置的自动符文问题。

**Comment by Z46I4W5476SJA** [comment]
> 日志和视频已查阅。
> 
> 这个软件目前为止 (v1.3.2 及以前) 并没有自动应用符文的功能，即使是小窗集成的 OP.GG，也需要**手动**设置符文。
> 
> 根据视频内容，它更像是客户端内置的自动符文问题。

我去  我还以为是软件自适应的     那想问一下  我每次进游戏之后   都有一个opgg的装备推荐  这个是自动的嘛    我好像也是自动配置的

**Comment by Hanxven** [comment]
OP.GG 目前仅作为参考，应用召唤师技能或符文，都需手动。它并不属于软件自动化流程的一部分。

**Comment by Z46I4W5476SJA** [comment]
> OP.GG 目前仅作为参考，应用召唤师技能或符文，都需手动。它并不属于软件自动化流程的一部分。
谢谢解答   感谢
