### ISSUE TITLE
[Bug] 没有启动开关

### ISSUE THREAD

**Issue by Cat0x1** [Hanxven/LeagueAkari#167]
![image](https://github.com/user-attachments/assets/5094ef99-3b2e-42e9-acae-69e385ca4bca)
应该有ge个启动按钮的，但不知道为什么没有，可能和我迁移过LOL文件有关吗？不知道这个软件是如何查询客户端位置的，我是否能够自己主动修改客户端位置呢？

**Comment by Hanxven** [comment]
这个检测基于**注册表**和**常用文件位置**检测，如果手动迁移过，那么软件可能就无法正确获取并验证目标位置文件的可访问性。

目前不支持手动设置位置。

**Comment by Cat0x1** [comment]
> 这个检测基于**注册表**和**常用文件位置**检测，如果手动迁移过，那么软件可能就无法正确获取并验证目标位置文件的可访问性。
> 
> 目前不支持手动设置位置。

我通过修改注册表“计算机\HKEY_USERS\S-1-5-21-748978406-4276388651-1577847879-1001\Software\Tencent\LOL” 后修复了这个问题
![image](https://github.com/user-attachments/assets/9b8cbeb1-2a71-4f79-82d7-660c5f2b7a9a)

**Comment by Hanxven** [comment]
超纲了，你是我梦寐以求的用户类型。

**Comment by Cat0x1** [comment]
> 超纲了，你是我梦寐以求的用户类型。

谢谢
