### ISSUE TITLE
[Feature Request] 游戏客户端不开启的情况下可以查询玩家战绩

### ISSUE THREAD

**Issue by Garker** [Hanxven/LeagueAkari#168]
作者你好
现在软件只有在游戏客户端开启的情况下才可以通过ID查询其他玩家战绩，可不可以改进一下为游戏不启动的情况下也可以查询其他玩家战绩

**Comment by randomjack34** [comment]
这将牵扯到法律问题，且难以实现

**Comment by Hanxven** [comment]
这个软件之所以需要连接客户端才能查询战绩，是因为需要通过客户端周期性地维持一些**必要的**会话信息。因此无法在没有客户端的情况下查询，更具体点，无法在没有登录的情况下查询 (意味着如果玩家在排队，也是无法查询任何东西的)。

---

通过一些特殊的方式，如搭建一个中心的服务器，可以在离线情况下由本软件的服务器代理查询，这也是市面上主流查询网站的做法。但是这会产生运营成本，同时也如楼上所言，会产生法律问题。
