### ISSUE TITLE
[BUG]查看游戏 这个功能 无法使用 一直获取

### ISSUE THREAD

**Issue by dnbllgtm** [Hanxven/LeagueAkari#17]
为了知道 BUG 的源头，请您尽可能描述：

1. 出现问题的版本。

2. 之前版本是否出现该问题？这将会帮助缩小排查范围。

3. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。

4. 这个问题具体是什么样子的？如果有截图或报错文字会更好。

5. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。

6. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。

感谢您的理解和配合。

**Comment by Hanxven** [comment]
请详细描述。

**Comment by dnbllgtm** [comment]
> 请详细描述。

杂项里的查看游戏 输入id后 无法获取游戏 id上面有条横线

**Comment by Hanxven** [comment]
游戏 ID 建议直接粘贴，并且只能输入纯数字。

之前的版本有点小问题，现在调整了下机制。
