### ISSUE TITLE
[Feature Request] 游戏内可以使用游戏外快捷键键功能

### ISSUE THREAD

**Issue by 00xiaoyang00** [Hanxven/LeagueAkari#171]
希望可以出一个在游戏内可以使用游戏外快捷键键功能，
现在游戏内好多其他软件的快捷键被英雄联盟屏蔽了
（比如截图  语音软件开关麦）
确实是有点不太方便

**Comment by Hanxven** [comment]
这似乎超过了本软件力所能及的范围，毕竟本软件的快捷键逻辑也是通过 hook 键盘输入来模拟的。
