### ISSUE TITLE
可以添加标记玩家功能吗

### ISSUE THREAD

**Issue by SKforever1** [Hanxven/LeagueAkari#19]
作者您好   leagueakali 这个插件特别好用  特别感谢您的无私付出

最近匹配总是碰到演员 恶意送人头的玩家  有些头疼
 
个人希望能添加一个  玩家黑名单 的功能  标记并给某个玩家添加标签  并在下次对局开始时在插件内提醒玩家

麻烦您了  谢谢！

**Comment by Hanxven** [comment]
您好，这个功能正在开发中。应该预计可以在下个版本完成。

![image](https://github.com/Hanxven/LeagueAkari/assets/52438792/7f48b7db-101c-43f6-9381-98d828038701)
