### ISSUE TITLE
查询召唤师战绩的页面，底部没有翻页按钮

### ISSUE THREAD

**Issue by ameigancai1** [Hanxven/LeagueAkari#21]
作者好，感谢开源了这么棒的工具~

- 问题：目前查询召唤师战绩的页面，翻页按钮位置目前是在顶部的。当下拉页面到底部的时候，如果想要翻页，需要返回到顶部点击下一页。
- 需求：是否可以在底部也加一个翻页的按钮呢？

**Comment by Hanxven** [comment]
感谢建议，已纳入考虑之中。
