### ISSUE TITLE
可以增加一个查看op.gg版本英雄的功能么😁

### ISSUE THREAD

**Issue by 516300502** [Hanxven/LeagueAkari#24]
就是个建议，没别的意思

**Comment by 516300502** [comment]
这个我还真不知道，不过101的数据感觉万年不更新的,没有op.gg的准确.

**Comment by light499960904** [comment]
这个比较好搞的做法是用无头浏览器获取OPGG的东西再进行处理，但是这个功能纯本机运行难度还是有点大了，需要自己做一个服务端存储对应的信息

**Comment by light499960904** [comment]
> 功能很好实现，但近期尝试过爬 OP.GG 的数据，发现以目前的水平很难完成。
> 
> 倒是 101 的数据源有点头绪。
> 
> 如果有公开的数据源（非私人运营的），欢迎推荐。

如果这个OPGG每天爬取一次（可以用别的方式实现，我可以尝试一下）然后作为版本更新的文件可行嘛？

**Comment by Hanxven** [comment]
> > 功能很好实现，但近期尝试过爬 OP.GG 的数据，发现以目前的水平很难完成。
> > 倒是 101 的数据源有点头绪。
> > 如果有公开的数据源（非私人运营的），欢迎推荐。
> 
> 如果这个OPGG每天爬取一次（可以用别的方式实现，我可以尝试一下）然后作为版本更新的文件可行嘛？

现在已经解决 OP.GG 数据的问题了，因为之前的努力方向错了，走了一些弯路。

但即使如此，怎么集成到现在的软件中是一个问题。对于不是 LCU 的内容，我希望避免太过于耦合。可能需要更多的设计和考虑。

**Comment by Hanxven** [comment]
该功能将在下个版本发布。
