### ISSUE TITLE
下等马功能

### ISSUE THREAD

**Issue by pcdd-group** [Hanxven/LeagueAkari#25]
https://cloud.tencent.com/developer/article/1987709

**Comment by Hanxven** [comment]
下等马功能很好实现，但这个软件永远不会直接实现这个功能，因为这会引起队友矛盾。

#20

**Comment by pcdd-group** [comment]
我也赞同，不过可以换一种形式，比如在软件对局页显示，仅自己可看。另外也可以用非歧视性词语来表示游戏水平，而不是几等马
