### ISSUE TITLE
[BUG]辅助窗口显示不全

### ISSUE THREAD

**Issue by zp880419** [Hanxven/LeagueAkari#26]
![ODBPT4WB)2P4$}UM)LJ9Y89](https://github.com/Hanxven/LeagueAkari/assets/51167177/37e455eb-b60a-4b9a-9b29-5b11c79f38ac)
一开始是正常的，后来突然变成这样了，显示不全，重置位置重启程序都不管用，而且选择是否置顶的按钮也不管用了。

**Comment by Hanxven** [comment]
有复现的方式吗？

在设置里关闭辅助窗口后再重新打开，会保持这种情况吗？

**Comment by zp880419** [comment]
> 有复现的方式吗？
> 
> 在设置里关闭辅助窗口后再重新打开，会保持这种情况吗？

不需要复现，现在是永远回不到正常了，关闭辅助窗口、重启客户端、重启电脑都试过。补充一下，我是4k分辨率，200%缩放，平时运行全屏程序退出来以后其他窗口也可能出现分辨率不对的问题，但是都可以恢复，这个辅助窗口恢复不了。

**Comment by Hanxven** [comment]
真是罕见的情况。这样，点进 `设置` -> `调试` -> `存储` -> `应用数据目录`，删除 `LeagueAkari.db`。看看是否能恢复正常。

**Comment by zp880419** [comment]
> 真是罕见的情况。这样，点进 `设置` -> `调试` -> `存储` -> `应用数据目录`，删除 `LeagueAkari.db`。看看是否能恢复正常。

删掉确实管用，然后设置都没了，拷回去以后就又那样了，看来是保存了这个错误的窗口大小。但是这个办法治标不治本啊，如果以后还会变，我不能每次都删配置文件吧。

**Comment by Hanxven** [comment]
下个版本会对窗口大小进行额外的校验，确实没考虑到由于缩放原因窗口信息被动态更改这件事。

您可以尝试：

- [delete_aux_window_setting.exe](https://mega.nz/file/p5wEWQ5R#5rxP9o7g1H_2bzUPh12RmS3TO9zapJSTNv10iKadl4s)：一个修正程序，会尝试删除掉当前目录下 LeagueAkari.db 中关于辅助窗口的设置项。

- [League Akari-1.2.1-rabi.2-win.7z](https://mega.nz/file/gwoTHL5R#OA3WTEA6nDO6aJLTHJ3sAifGMZ-vM9T1Z4MRjo25HyA)：一个未发布的测试版本，这个版本会锁定辅助窗口的大小。

感谢您的理解。

**Comment by zp880419** [comment]
测试了好用，感谢。另外有个小建议，自动禁用功能似乎没有像自动预选一样可以只亮出不锁定的选项，能不能加上呢？

**Comment by Hanxven** [comment]
> 测试了好用，感谢。另外有个小建议，自动禁用功能似乎没有像自动预选一样可以只亮出不锁定的选项，能不能加上呢？

这个版本仍存在问题。发现会出现拖动不跟手的情况。您可以等待下一次更新。

关于自动禁用的锁定策略问题：当时考虑亮出的意义不是很大，并且也没有类似于同步匹配模式需要立即占位秒抢英雄的需求。所以目前固定是直接完成锁定的。

总之我会考虑添加此功能。
