### ISSUE TITLE
[FEATURE] 副窗口支持皮肤选择

### ISSUE THREAD

**Issue by gray2020** [Hanxven/LeagueAkari#27]
目前皮肤选择在 工具 -> 过程中 -> 皮肤选择，选起来很麻烦。
希望把 皮肤选择 放到辅助窗口里，方便操作。

**Comment by Hanxven** [comment]
感谢您的建议，将列入下个版本的更新中。

在下个版本后，在辅助窗口时，若存在可选择的任何皮肤，则提供一个列表设置器。

将可以加入群组以获取添加了此功能最新的测试版本。
