### ISSUE TITLE
[BUG]disconnected

### ISSUE THREAD

**Issue by WanCixiong** [Hanxven/LeagueAkari#30]
版本:1.2.0
WIN10
管理员权限
![Snipaste_2024-05-07_20-13-21](https://github.com/Hanxven/LeagueAkari/assets/58263178/e6375f26-e8cf-4c5a-8b8c-681498cee64f)
![Snipaste_2024-05-07_20-16-57](https://github.com/Hanxven/LeagueAkari/assets/58263178/de417b04-21ef-4651-84cc-90cbceed1dfd)

**Comment by Hanxven** [comment]
似乎无法连接到游戏客户端。方便提供一下日志文件吗？

它位于 `设置` -> `调试` 中，打开日志目录将其中的文件打包即可。

> 这个文件可能会包含一些个人信息。

**Comment by WanCixiong** [comment]
已发送到您的邮箱

**Comment by Hanxven** [comment]
收到您的邮件。我注意到端口号使用了 `5062`，这似乎不是一个正常的值，我怀疑是命令行解析错误造成的。

为了确认是否是这个错误，想请您：

1. 右键开始菜单，找到 `终端管理员` 或 Powershell 管理员 类似的东西。

2. 在游戏客户端运行时，粘贴内容并回车：
```bat
wmic process where "name like '%LeagueClientUx.exe%'" get commandline
```

3. 提供所有输出。

**Comment by WanCixiong** [comment]
已发送

**Comment by Hanxven** [comment]
命令行中发现 `"--remoting-auth-token=Rhttp://some.urlcbsAMQ"`，以及 `"--riotclient-auth-token=XXXXXXXXXXXXXX"`。这些不是命令行中会出现的正常格式。除了这两个还有若干命令行格式不正确，我不确定是 Gmail 转换的问题或原本就是这样。

`--remoting-auth-token` 是连接到 LCU 的必须密钥，每次启动都会随机生成。

**Comment by WanCixiong** [comment]
xxxxx 是我手动更改的

**Comment by WanCixiong** [comment]
稍后我将重新安装一次lol

**Comment by Hanxven** [comment]
> xxxxx 是我手动更改的

常见的格式应该类似于此：

```
d:/wegameapps/Ӣ      /LeagueClient/LeagueClientUx.exe "--riotclient-auth-token=6rxWlUY8AVnfi--V_GluvQ" "--riotclient-app-port=55662" "--riotclient-tencent" "--no-rads" "--disable-self-update" "--region=TENCENT" "--locale=zh_CN" "--t.lcdshost=tj100-feapp.lol.qq.com" "--t.chathost=tj100-ejabberd.lol.qq.com" "--rso-auth.url=https://prod-rso.lol.qq.com:3000" "--rso_platform_id=TJ100" "--rso_original_platform_id=WT3_NEW" "--rso-auth.client=lol" "--t.location=loltencent.tjhequ1.tj100" "--tglog-endpoint=https://tglogsz.datamore.qq.com/lolcli/report/" "--ccs=https://tj100-cc.lol.qq.com:8093" "--entitlements-url=https://tj100-entitlements.lol.qq.com:28088/api/token/v1" "--dradis-endpoint=http://some.url" "--remoting-auth-token=ghtkyioU9eULdpHBB_M3Gg" "--app-port=55766" "--install-directory=d:\wegameapps\英雄联盟\LeagueClient" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--crash-reporting=" "--crash-environment=TJ100" "--app-log-file-path=d:/wegameapps/Ӣ      /LeagueClient/../Game/Logs/LeagueClient Logs/2024-05-08T22-20-51_6520_LeagueClient.log" "--app-pid=6520" "--output-base-dir=d:/wegameapps/英雄联盟/LeagueClient/../Game" "--no-proxy-server" "--ignore-certificate-errors"
```

---

> 稍后我将重新安装一次lol

应该和游戏客户端关系不大。

也可以执行以下命令：

```powershell
Get-CimInstance -Query 'SELECT * from Win32_Process WHERE name LIKE ''LeagueClientUx.exe'''  |  Select-Object -ExpandProperty CommandLine
```

检查是否能获取正确的格式。

> 命令行中无敏感数据，仅包括大区信息和游戏目录。

**Comment by WanCixiong** [comment]
PS C:\Windows\system32> Get-CimInstance -Query 'SELECT * from Win32_Process WHERE name LIKE ''LeagueClientUx.exe'''  |  Select-Object -ExpandProperty CommandLine
c:/game/lol/英雄联盟(26)/LeagueClient/LeagueClientUx.exe "--riotclient-auth-token=2W4eII6kxecoj0eyGab3JQ" "--riotclient-app-port=5007" "--riotclient-tencent" "--no-rads" "--disable-self-update" "--region=TENCENT" "--locale=zh_CN" "--t.lcdshost=tj100-feapp.lol.qq.com" "--t.chathost=tj100-ejabberd.lol.qq.com" "--rso-auth.url=https://prod-rso.lol.qq.com:3000" "--rso_platform_id=TJ100" "--rso_original_platform_id=WT3_NEW" "--rso-auth.client=lol" "--t.location=loltencent.tjhequ1.tj100" "--tglog-endpoint=https://tglogsz.datamore.qq.com/lolcli/report/" "--ccs=https://tj100-cc.lol.qq.com:8093" "--entitlements-url=https://tj100-entitlements.lol.qq.com:28088/api/token/v1" "--dradis-endpoint=http://some.url" "--remoting-auth-token=RHJOxdVkIHAek26XcbsAMQ" "--app-port=5062" "--install-directory=c:\game\lol\鑻遍泟鑱旂洘(26)\LeagueClient" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--crash-reporting=" "--crash-environment=TJ100" "--app-log-file-path=c:/game/lol/英雄联盟(26)/LeagueClient/../Game/Logs/LeagueClient Logs/2024-05-08T20-29-54_2100_LeagueClient.log" "--app-pid=2100" "--output-base-dir=c:/game/lol/鑻遍泟鑱旂洘(26)/LeagueClient/../Game" "--no-proxy-server" "--ignore-certificate-errors"

**Comment by Hanxven** [comment]
看起来没问题啊，使用 `WMIC` 获取的也是 `"--remoting-auth-token=RHJOxdVkIHAek26XcbsAMQ"` 吗？

如果之前的 `WMIC` 获取到的 `--remoting-auto-token` 是手动修改过的，那么这就是个未知的玄学问题了。

看起来暂时没有解决方法。我会持续关注这个问题。

**Comment by WanCixiong** [comment]
这是第一次的

PS C:\Windows\system32> wmic process where "name like '%LeagueClientUx.exe%'" get commandline
CommandLine                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
c:/game/lol/英雄联盟(26)/LeagueClient/LeagueClientUx.exe "--riotclient-auth-token=2W4eII6kxecoj0eyGab3JQ" "--riotclient-app-port=5007" "--riotclient-tencent" "--no-rads" "--disable-self-update" "--region=TENCENT" "--locale=zh_CN" "--t.lcdshost=tj100-feapp.lol.qq.com" "--t.chathost=tj100-ejabberd.lol.qq.com" "--rso-auth.url=https://prod-rso.lol.qq.com:3000" "--rso_platform_id=TJ100" "--rso_original_platform_id=WT3_NEW" "--rso-auth.client=lol" "--t.location=loltencent.tjhequ1.tj100" "--tglog-endpoint=https://tglogsz.datamore.qq.com/lolcli/report/" "--ccs=https://tj100-cc.lol.qq.com:8093" "--entitlements-url=https://tj100-entitlements.lol.qq.com:28088/api/token/v1" "--dradis-endpoint=http://some.url" "--remoting-auth-token=RHJOxdVkIHAek26XcbsAMQ" "--app-port=5062" "--install-directory=c:\game\lol\鑻遍泟鑱旂洘(26)\LeagueClient" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--crash-reporting=" "--crash-environment=TJ100" "--app-log-file-path=c:/game/lol/英雄联盟(26)/LeagueClient/../Game/Logs/LeagueClient Logs/2024-05-08T20-29-54_2100_LeagueClient.log" "--app-pid=2100" "--output-base-dir=c:/game/lol/鑻遍泟鑱旂洘(26)/LeagueClient/../Game" "--no-proxy-server" "--ignore-certificate-errors"

这是第二次的
PS C:\Windows\system32> Get-CimInstance -Query 'SELECT * from Win32_Process WHERE name LIKE ''LeagueClientUx.exe'''  |  Select-Object -ExpandProperty CommandLine
c:/game/lol/英雄联盟(26)/LeagueClient/LeagueClientUx.exe "--riotclient-auth-token=2W4eII6kxecoj0eyGab3JQ" "--riotclient-app-port=5007" "--riotclient-tencent" "--no-rads" "--disable-self-update" "--region=TENCENT" "--locale=zh_CN" "--t.lcdshost=tj100-feapp.lol.qq.com" "--t.chathost=tj100-ejabberd.lol.qq.com" "--rso-auth.url=https://prod-rso.lol.qq.com:3000" "--rso_platform_id=TJ100" "--rso_original_platform_id=WT3_NEW" "--rso-auth.client=lol" "--t.location=loltencent.tjhequ1.tj100" "--tglog-endpoint=https://tglogsz.datamore.qq.com/lolcli/report/" "--ccs=https://tj100-cc.lol.qq.com:8093" "--entitlements-url=https://tj100-entitlements.lol.qq.com:28088/api/token/v1" "--dradis-endpoint=http://some.url" "--remoting-auth-token=RHJOxdVkIHAek26XcbsAMQ" "--app-port=5062" "--install-directory=c:\game\lol\鑻遍泟鑱旂洘(26)\LeagueClient" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--crash-reporting=" "--crash-environment=TJ100" "--app-log-file-path=c:/game/lol/英雄联盟(26)/LeagueClient/../Game/Logs/LeagueClient Logs/2024-05-08T20-29-54_2100_LeagueClient.log" "--app-pid=2100" "--output-base-dir=c:/game/lol/鑻遍泟鑱旂洘(26)/LeagueClient/../Game" "--no-proxy-server" "--ignore-certificate-errors"

**Comment by KusanagiKW** [comment]
我也出现了一样的问题

**Comment by Hanxven** [comment]
https://mega.nz/file/QhYxhaLR#crcPEnnNZVa2H4m78vNOmtcuA1XPtO8nW7m0-oqKtVg

请尝试一下这个版本。
