### ISSUE TITLE
[请求]请求添加一个镜像翻转功能

### ISSUE THREAD

**Issue by meteorsthink** [Hanxven/LeagueAkari#31]
比如说此次在出生在红色方，希望有一个功能可以将地图翻转，视角切到蓝色方

**Comment by Hanxven** [comment]
我不是魔法师，这个真做不到

**Comment by meteorsthink** [comment]
这个是可以实现的，我这里有别人写的一个实现文件，您可以以此作为参考，我猜测实现方式是通过读写驱动，但是由于我语言用的C，不懂上层语言，所以无法逆推源码，麻烦您看下。
https://www.lanzoub.com/iyars1ybn6vc
密码:9zu5

**Comment by Hanxven** [comment]
逆向不是一般的技术活，另外这是会直接修改游戏端的行为。
