### ISSUE TITLE
希望添加启动进程以及窗口最小化到右下角。

### ISSUE THREAD

**Issue by gonfei** [Hanxven/LeagueAkari#33]

**Comment by Hanxven** [comment]
最小化到右下角已在 1.2.1 中完成。

“启动进程” 可否详细描述该需求？

**Comment by gonfei** [comment]
> 最小化到右下角已在 1.2.1 中完成。
> 
> “启动进程” 可否详细描述该需求？

1. 最小化到右下角，在我这是失效的，它只是最小化到状态栏了，并没有缩小到右下角。（windows11）
2. 启动进程就是把启动lol客户端按钮，我自己也想了一下，直接在桌面发送lol快捷方式也一样。（这个功能不重要）
3. 主要的还是希望加入出装和符文推荐吧。我是两个软件一起使用的，符文和装备推荐软件是叫champr,也是开源软件，它提供了多个源用于更换装备和符文。（他的装备推荐选择源后可以自动生效，符文则需要手动选择）。可以参考一下，软件开源地址：https://github.com/cangzhang/champ-r
下面是软件的界面截图：
![image](https://github.com/Hanxven/LeagueAkari/assets/68487358/fe8424a7-d094-4234-b576-2e58e919593d)

**Comment by gonfei** [comment]
> 只有在关闭的时候才会触发最小化到右下角（根据配置的默认行为，直接退出程序或仅最小化到托盘区）。因为最小化我还是打算保持系统默认的最小化行为，毕竟大部分软件的逻辑也是这样。
> 
> 关于自动符文，我没有数据源。ChampR 这个项目我也研究过，它使用的数据源是私有的，我无法依赖别人的私有数据。
> 
> 但是 ChampR 提到的网站列表给了我一些思路，我或许可以通过某些手段来爬取这些公开站点的内容，并抽象成外部数据源，以保证软件的核心功能和这些东西不耦合。
> 
> 但进度可能会很靠后了，毕竟这个项目目前只有我一个人。

最小化问题在我更新到1.2.1已经解决了。目前功能基本满足使用，至于符文和装备推荐，可以配合champr使用，并不影响游戏体验。

期待您有更多的功能上线，感谢您的辛勤付出和无私奉献。

**Comment by Hanxven** [comment]
在后期可能会慢慢支持的。目前还在考虑怎么处理这些外部数据源。
