### ISSUE TITLE
[建议] 大乱斗buff, 显示优化

### ISSUE THREAD

**Issue by zhengchalei** [Hanxven/LeagueAkari#34]
在选择英雄的框上面, 是否可以使用红绿颜色区分 增益或者减益buff

**Comment by Hanxven** [comment]
请详细描述您的需求。有图最好

**Comment by zhengchalei** [comment]
![微信截图_20240515023350](https://github.com/Hanxven/LeagueAkari/assets/31665079/179bd1ec-e8b1-4294-b349-63f064a97cd7)
类似这样的, 能快速区分, 增益或减益

**Comment by Hanxven** [comment]
可行。

将提供一个颜色边框，若是加强，则使用绿色；若是削弱，则使用红色；若两者都有，则上半部分用绿色，下半部分用红色。

**Comment by 824348454** [comment]
> ![微信截图_20240515023350](https://private-user-images.githubusercontent.com/31665079/330553439-179bd1ec-e8b1-4294-b349-63f064a97cd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NDkzNjAsIm5iZiI6MTcxNTk0OTA2MCwicGF0aCI6Ii8zMTY2NTA3OS8zMzA1NTM0MzktMTc5YmQxZWMtZThiMS00Mjk0LWIzNDktNjNmMDY0YTk3Y2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEyMzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNjNhYTllNzRmOTZhYWY4Y2Q1MTk4YTBmYmFmZTZjNDEzMTA1MjdmN2U4MmI0MWVlY2NjNGY1NjRhODM5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoRe4lXC2xagxS5y-DlfDlkXWPZEY3yiGreDngeAcZo)类似这样的, 能快速区分, 增益或减益

然后最好鼠标移上去之后能浮现具体buff

**Comment by zhengchalei** [comment]
> 可行。
> 
> 将提供一个颜色边框，若是加强，则使用绿色；若是削弱，则使用红色；若两者都有，则上半部分用绿色，下半部分用红色。

表示觉得很赞

**Comment by Hanxven** [comment]
> > ![微信截图_20240515023350](https://private-user-images.githubusercontent.com/31665079/330553439-179bd1ec-e8b1-4294-b349-63f064a97cd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NDkzNjAsIm5iZiI6MTcxNTk0OTA2MCwicGF0aCI6Ii8zMTY2NTA3OS8zMzA1NTM0MzktMTc5YmQxZWMtZThiMS00Mjk0LWIzNDktNjNmMDY0YTk3Y2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEyMzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNjNhYTllNzRmOTZhYWY4Y2Q1MTk4YTBmYmFmZTZjNDEzMTA1MjdmN2U4MmI0MWVlY2NjNGY1NjRhODM5MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoRe4lXC2xagxS5y-DlfDlkXWPZEY3yiGreDngeAcZo)类似这样的, 能快速区分, 增益或减益
> 
> 然后最好鼠标移上去之后能浮现具体buff

很遗憾，您提供的图片无法查看。

**Comment by Hanxven** [comment]
群内（QQ: 301157623）近期打包了一个测试版本。如果您有兴趣，可以使用并提出具体建议。
