### ISSUE TITLE
[建议] 增加英雄组合推荐

### ISSUE THREAD

**Issue by 1738352551** [Hanxven/LeagueAkari#36]
# 功能描述:
在英雄选择阶段，工具根据己方英雄选择情况推荐选择英雄，比如说我是辅助，adc选择了一个英雄之后，工具可以根据lol101里面**_最佳双排_**的数据推荐我使用哪个辅助。

# 截图:
![image](https://github.com/Hanxven/LeagueAkari/assets/32236403/459fa3d5-3cf4-490f-a4f8-cdb4db6b890b)

# 接口:
https://faas-6831.native.qq.com/faas/6831/1371/getRankDouble

![image](https://github.com/Hanxven/LeagueAkari/assets/32236403/57ea3cd4-b9ad-43b0-a01f-6c36f1728b9a)

**Comment by Hanxven** [comment]
已纳入考虑之中。

**Comment by Hanxven** [comment]
有较大实现难度，将不考虑实现。
