### ISSUE TITLE
可以出一个运行教程吗 还是有软件~

### ISSUE THREAD

**Issue by 319707767** [Hanxven/LeagueAkari#40]
找不到运行方法...

**Comment by Hanxven** [comment]
无意义内容。

**Comment by Hanxven** [comment]
有关软件运行方法，已经在主页介绍中。

你可以通过下载 Releases 中的发行版本，或进入群聊获取。

解压后执行主程序 `LeagueAkari.exe`。

确保你下载的不是**源代码**。
