### ISSUE TITLE
[建议]在游戏中增加一个计时器小窗口方便记录对方闪现时间

### ISSUE THREAD

**Issue by adz6666** [Hanxven/LeagueAkari#41]
为了知道 BUG 的源头，请您尽可能描述：

1. 出现问题的版本。

2. 之前版本是否出现该问题？这将会帮助缩小排查范围。

3. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。

4. 这个问题具体是什么样子的？如果有截图或报错文字会更好。

5. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。

6. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。

感谢您的理解和配合。

**Comment by Hanxven** [comment]
暂时无法实现。
