### ISSUE TITLE
推荐装备天赋开源接口项目

### ISSUE THREAD

**Issue by gonfei** [Hanxven/LeagueAkari#43]
地址：https://github.com/Ninohana/data-long

**Comment by Hanxven** [comment]
暂时不会依赖私人数据接口。将考虑使用 OP.GG API。

**Comment by gonfei** [comment]
可以 也可以加入101的推荐源虽然烂但能用-------- 原始邮件 --------发件人： Hanxven ***@***.***>日期： 2024年6月7日周五 10:21收件人： Hanxven/LeagueAkari ***@***.***>抄送： GONFEI ***@***.***>, Author ***@***.***>主    题： Re: [Hanxven/LeagueAkari] 推荐装备天赋开源接口项目 (Issue #43)
暂时不会依赖私人数据接口。将考虑使用 OP.GG API。
