### ISSUE TITLE
[疑问] 这个tag，是仅自己可见吗？还是能共享给各位

### ISSUE THREAD

**Issue by xixiaxixi** [Hanxven/LeagueAkari#44]
![image](https://github.com/Hanxven/LeagueAkari/assets/24312323/312abcec-05c5-47af-8718-5def25d9705e)

**Comment by Hanxven** [comment]
是的，这是仅自己可见的内容，因为本软件不会上传任何玩家数据。

您可以通过 `调试` 设置项中的应用目录，找到存放了这些信息的 `LeagueAkari.db` 数据库文件目录。
