### ISSUE TITLE
[建议]在不启动客户端的情况下使用部分功能

### ISSUE THREAD

**Issue by MSPAAG** [Hanxven/LeagueAkari#45]
1.情景描述：在查朋友战绩时，发现leagueakari需要登录lol才能使用；进入服务器时，发现电一需要排队；排队之后，发现进错区了，查不到战绩；遂改区重登，又排队。
2.需求：在不打开lol客户端的情况下使用包括查询玩家在内的部分功能；查询时增加非当前大区查询/全大区查询功能

**Comment by Hanxven** [comment]
无法做到。因为数据**完全**来自于 LCU API。换言之，无法在未启动客户端时是功能，且部分接口需要客户端内部登录后才能使用。排队过程中，玩家属于未登录状态。
