### ISSUE TITLE
弹出框显示不完整

### ISSUE THREAD

**Issue by Jerry95000** [Hanxven/LeagueAkari#46]
1.2.1版本，自动化弹出框显示残缺，
<img width="142" alt="Snipaste_2024-06-09_12-25-24" src="https://github.com/Hanxven/LeagueAkari/assets/117874864/62c42fdf-f1f1-4c11-9e60-70d934a5206d">
如图

**Comment by Hanxven** [comment]
现阶段，请在设置项中重置辅助窗口。（设置，通用，辅助窗口相关）

有关此问题会在之后版本尝试解决。
