### ISSUE TITLE
[建议]如图，添加一个战绩类型，有时候只查询排位即可，极地大乱斗这种人头很多的KDA没什么参考意义；发送战绩时候可以添加个上等马下等马排序，一目了然

### ISSUE THREAD

**Issue by Silencestardust** [Hanxven/LeagueAkari#49]
![QQ截图20240610185536](https://github.com/Hanxven/LeagueAkari/assets/150066925/9eed07e7-871e-48e2-af08-69bceea16db8)
![QQ截图20240610185557](https://github.com/Hanxven/LeagueAkari/assets/150066925/f5549a3b-ac9e-4893-a2ce-2358d761fd7b)

**Comment by freeok** [comment]
> ![QQ截图20240610185536](https://private-user-images.githubusercontent.com/150066925/338156513-9eed07e7-871e-48e2-af08-69bceea16db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDU1ODcsIm5iZiI6MTcxOTE0NTI4NywicGF0aCI6Ii8xNTAwNjY5MjUvMzM4MTU2NTEzLTllZWQwN2U3LTg3MWUtNDhlMi1hZjA4LTY5YmNlZWExNmRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxMjIxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTZiNmIyZTU3ODFkOWY3ZjRmZjJkNGQwNWVmY2FkMjdjOWY2M2I5ZjYzMGZlZTRiMmU1MWY0ZmEyZWZlOTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7iDAWHb6s6klj2Am-2AWqIbHfzjGCh4dMsfduCe9T2k) ![QQ截图20240610185557](https://private-user-images.githubusercontent.com/150066925/338156521-f5549a3b-ac9e-4893-a2ce-2358d761fd7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDU1ODcsIm5iZiI6MTcxOTE0NTI4NywicGF0aCI6Ii8xNTAwNjY5MjUvMzM4MTU2NTIxLWY1NTQ5YTNiLWFjOWUtNDg5My1hMmNlLTIzNThkNzYxZmQ3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxMjIxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDg0NWZhODI5YWFhMmVhYzRkNzkzN2I2OWI5OWE3NjcyOTkxNmFjY2M3YjFlMDFhZDU2YzBmY2JkMjkyOWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-0XnoWKZwGVoFw-HxeF6Yiq2wuqUKBg2TigIjE5kD7s)

https://github.com/Hanxven/LeagueAkari/issues/25
https://github.com/Hanxven/LeagueAkari/issues/20

**Comment by Hanxven** [comment]
#37 重复问题
