### ISSUE TITLE
[BUG] 使用快捷键关闭窗口，再打开会报异常

### ISSUE THREAD

**Issue by Ifover** [Hanxven/LeagueAkari#50]
为了知道 BUG 的源头，请您尽可能描述：

1. 出现问题的版本。
v1.2.1

2. 之前版本是否出现该问题？这将会帮助缩小排查范围。
大概率也有

3. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。
使用Ctrl+W或者Alt+F4关闭窗口，双击右下角小图标打开窗口是复现。
也不是什么大问题，因为个人原因鼠标手势用了好几年了有点改不掉了。
然后关闭窗口手势基本上就是触发这两个快捷键之一，但是试了这两个都会触发这个异常

4. 这个问题具体是什么样子的？如果有截图或报错文字会更好。
![image](https://github.com/Hanxven/LeagueAkari/assets/7272162/dda23d42-a1eb-48ce-a804-7b1349feaa81)

5. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。
Windows 11 23H2 （22631.3007）

7. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。
`[2024-06-11T08:23:32.281Z] [league-akari] [error] uncaughtException: Object has been destroyed TypeError: Object has been destroyed
    at toggleMinimizeAndFocus (D:\Tools\League.Akari\resources\app.asar\out\main\main.js:25:38818)
    at Tray.<anonymous> (D:\Tools\League.Akari\resources\app.asar\out\main\main.js:25:26118)
    at Tray.emit (node:events:518:28)`

**Comment by Hanxven** [comment]
该问题已经发现并定位，将于下版本实装。
