### ISSUE TITLE
[建议]自动化能否设置添加mute all功能

### ISSUE THREAD

**Issue by ShimaRain** [Hanxven/LeagueAkari#51]
大乱斗习惯mute all

**Comment by BakaFT** [comment]
这个软件不是有一个发送自定义文本的功能吗？把发送文本内容换成`/mute all`就行了`

似乎是模拟键盘操作吧，没细看，

https://github.com/Hanxven/LeagueAkari?tab=readme-ov-file#28-%E6%B2%A1%E4%BB%80%E4%B9%88%E7%94%A8%E7%9A%84%E5%8A%9F%E8%83%BD

https://github.com/Hanxven/LeagueAkari/blob/98bb9f87b7d2d5ca6bb292c89f4d9844c3967a56/src/main/modules/custom-keyboard-sequence/index.ts#L32

**Comment by ShimaRain** [comment]
想要的是自动化，这个和我tab手动mute没有区别

**Comment by Hanxven** [comment]
我无法修改游戏客户端，该功能很难实现。

**Comment by ShimaRain** [comment]
好的，谢谢你的解答👌

**Comment by ShimaRain** [comment]
> 我无法修改游戏客户端，该功能很难实现。

好的，感谢你的回复
