### ISSUE TITLE
大乱斗[BUG]

### ISSUE THREAD

**Issue by zp880419** [Hanxven/LeagueAkari#54]
大乱斗在点击roll点换英雄的瞬间会闪退客户端消失，这个问题出现的频率越来越高。

**Comment by Hanxven** [comment]
真是个头疼的问题。

在闪退时，有开启了任何和乱斗相关的功能吗？

**Comment by zp880419** [comment]
我记得自动抢英雄的功能，我有时开着有时关着，但都会出现客户端消失的问题，其他功能基本也都开着。

**Comment by Hanxven** [comment]
#18 重复问题。已关闭。
