### ISSUE TITLE
[BUG]导致大厅黑屏

### ISSUE THREAD

**Issue by PancrasT** [Hanxven/LeagueAkari#55]
最新的1.2.1版本中，开启了软件进行大乱斗后，回不到大厅，会导致黑屏，一开始以为是自动ban选和自动匹配接收操作太快了导致的，后面关闭那些自动功能只留自动抢英雄也会出现此情况

**Comment by Hanxven** [comment]
是否开启了自动返回房间和自动点赞相关功能？这两个功能的联动目前来看会出现明显的 BUG。

因为近期较忙，长期没有更新，所以 1.2.1 版本中很多内容都已经失效了。请等待 1.2.2 版本相关更新和修复。

**Comment by Hanxven** [comment]
#18 重复问题。已关闭。

**Comment by Hanxven** [comment]
经测试，该问题在新版本仍未完全修复。
