### ISSUE TITLE
是否有战时数据统计？

### ISSUE THREAD

**Issue by zhangzw218** [Hanxven/LeagueAkari#56]
比如战时实时统计照成的总伤害、承伤、治疗之类的。
主要是想看伤害和承伤。
顺便揪出来大乱斗到底谁在抢人头还不输出。。

**Comment by BakaFT** [comment]
请分清 客户端 和 游戏本身，这是两个东西

不读内存的情况下是做不到的，但读内存已被明令禁止，所以无法可靠地实现
