### ISSUE TITLE
请问可以加一套大乱斗评分系统吗？可能任务比较大qaq

### ISSUE THREAD

**Issue by yml123456789** [Hanxven/LeagueAkari#57]
kda在大乱斗里面参考价值有点低，大乱斗评分可以侧重输出占比，在加上少量权重的kda。 这是C位的评分标准
工具人的话可以看提供的控制时长（不知道这个数据能不能获得）；承受伤害量（这个一定要加上自我缓和的伤害），护盾量，治疗量，给队友提供的增伤量（比如帝国指令，娜美E，风女E这种，深渊面具）
战士的话就是输出 加承受伤害。

**Comment by yml123456789** [comment]
可以参考lol客户端的评分（S A B），或者wegame的评分系统，感觉都还可以

**Comment by Hanxven** [comment]
> 可以参考lol客户端的评分（S A B），或者wegame的评分系统，感觉都还可以

遗憾的是我目前并不了解 WeGame 和客户端的评分机制。如果有具体的评分标准或方法，我很乐意快速地实现它。
