### ISSUE TITLE
[FEATURE REQUEST] 按键配置保存

### ISSUE THREAD

**Issue by comtnt** [Hanxven/LeagueAkari#58]
### 需求来源
用户经常更换账号导致频繁更改游戏按键配置，消耗大量时间。因此，需要一个方便的解决方案来管理和切换按键配置。

### 实现方式
- **增加按键配置列表页**：在应用中增加一个页面，用于展示所有按键配置，并将其持久化存储到本地数据库。
- **新增和删除按键配置**：
  - 用户可以将当前的按键配置保存到按键配置列表中。
  - 用户也可以从列表中删除不需要的按键配置。
- **切换按键配置**：用户可以从按键配置列表中选择任意一个配置，并将其恢复为当前的按键配置。

这样一来，用户在更换账号时只需简单地在列表中选择所需的按键配置即可，大大节省了时间和精力。

**Comment by comtnt** [comment]
- 配置文件：英雄联盟\Game\Config\PersistedSettings.json

**Comment by Hanxven** [comment]
于 v1.3.0 版本后，添加一个设置该文件只读的快捷方式。
