### ISSUE TITLE
[Feature Request] 建议增加一个付费多功能版本，和一个免费基础版本。就像很多查战绩网站一样需要收费查询

### ISSUE THREAD

**Issue by pangdd123** [Hanxven/LeagueAkari#59]
毕竟白嫖是不长久的，付费才有更多的动力持续更新嘛，只需要参考市场价别那么黑心就行！！！！！！
作者还有一些功能没有完善，希望能参考WeGame进行完善比如
1增加一个查询这个人最擅长的五个英雄以及他对应的场次
2像WeGame一样可以查看这个人历史段位信息

**Comment by Hanxven** [comment]
League Akari 是免费且开源的软件，将永远不会收费，也不会开放任何捐赠渠道。

如果您中意此项目，请 Star。感谢。
