### ISSUE TITLE
exe打不开

### ISSUE THREAD

**Issue by soupuuc** [Hanxven/LeagueAkari#6]
你好请问 v1.1.1压缩包内的exe 打不开 应该如何操作呢

**Comment by Hzh201wl** [comment]
我也打不开啊用旧版本也打不开。。

**Comment by Hanxven** [comment]
这是两个测试版本。看看是否有用。

https://mega.nz/file/QgJVTAIJ#-6g19asxTxTtACaGV3DGlwzQKuGE1r4_1jqVQNUWrRs

https://mega.nz/file/Qo4WDZrT#0JBtLV8DQ0BjL6hmqZez4t2PORzsrq5fWT8XUGu0NTo

蓝奏云我这边网络上传不上去。

**Comment by soupuuc** [comment]
可以了 谢谢 大大 非常感谢

**Comment by Hanxven** [comment]
> 可以了 谢谢 大大 非常感谢

您可以说一下是哪个版本可以运行吗？我将在下个版本调整

**Comment by soupuuc** [comment]
我用的是 test1，这个能用了。  非常感谢大大 辛苦啦✧٩(ˊωˋ*)و✧
