### ISSUE TITLE
[Feature Request] 建议添加一键弹出作者的美照功能

### ISSUE THREAD

**Issue by wniarai** [Hanxven/LeagueAkari#60]
希望添加一个新的功能，为了让我们更好的膜拜作者，添加一个一键弹出作者美照的功能，建议添加一个窗口，里面是作者的美照，可以随机显示，弄一个button，点击还能随机切换

**Comment by Hanxven** [comment]
无用 Issue，请不要在 Issue 区发送无关内容。
