### ISSUE TITLE
请求增加2个功能

### ISSUE THREAD

**Issue by pangdd123** [Hanxven/LeagueAkari#61]
1希望增加一个查询这个人最擅长的五个英雄以及他对应的场次的功能
2像WeGame一样可以查看这个人历史段位信息的功能

**Comment by Hanxven** [comment]
第二个功能似乎难以实现，LCU 接口没有涉及相关内容。

WeGame 使用了另一套系统，和 LCU 接口有若干差异。

**Comment by Hanxven** [comment]
第一个需求应该可以用过成就系统接口获得。
