### ISSUE TITLE
[Feature Request]  大乱斗隐藏分

### ISSUE THREAD

**Issue by LeeZ1Q** [Hanxven/LeagueAkari#64]
对局部分加入大乱斗隐藏分查询

参考链接：
[大乱斗也有段位了？免费查自己的官方ELO隐藏分](https://www.bilibili.com/video/BV1Ew4m1a7U6/?spm_id_from=333.1365.list.card_archive.click&vd_source=68f2bb9642bcb5153457b12f9e91114f)
[究极干货 | elo分的来源、查询、增减以及匹配机制](https://tieba.baidu.com/p/9048904229?see_lz=1)
[charles安装和激活教程](https://www.cnblogs.com/shaohuang/p/17505696.html)

**Comment by Hanxven** [comment]
虽说是早已知道的特性，但难以集成到本软件中。因为这个数据来自 WeGame，而本软件只是一个英雄联盟客户端工具。
