### ISSUE TITLE
希望增加功能：跳过结算界面/修复无限加载

### ISSUE THREAD

**Issue by opkhkh** [Hanxven/LeagueAkari#67]
希望增加功能：跳过结算界面/修复无限加载
英雄联盟游戏结束有时候无法加载结算界面，我之前使用过这两个助手，才发现有这个功能
https://github.com/watchingfun/Joi
https://github.com/Zzaphkiel/Seraphine

**Comment by BakaFT** [comment]
![QQ_1721126619391](https://github.com/user-attachments/assets/5e2c8ff8-8fd5-4381-a1df-a657ae9a176d)

我找到了个好东西

**Comment by Hanxven** [comment]
属于已有功能。
