### ISSUE TITLE
根据队列筛选玩家战绩

### ISSUE THREAD

**Issue by opkhkh** [Hanxven/LeagueAkari#68]
有时候筛选排位记录，结果没有符合筛选条件的目标，我猜测目前筛选逻辑是在当前页20场游戏记录中筛选排位赛，如果这20场没有排位记录，结果就会为空

但我认为多数情况下，玩家希望的是，直接筛选所有排位记录，而不仅仅在当前页20场中筛选排位记录，希望修改这个功能。

wegame就是这种筛选模式，修改后，无论筛选哪种游戏模式，每页都有20条筛选结果。

![2024-07-16_171510](https://github.com/user-attachments/assets/087baa04-0e46-4381-b07e-179d2e8322d6)

**Comment by Hanxven** [comment]
WeGame 使用的战绩系统和 LCU API 并不相同。

仅基于 LCU API 或 SGP API 是无法做到筛选的，因为接口本身就没提供筛选功能。

**Comment by Hanxven** [comment]
将提上日程。
