### ISSUE TITLE
[Feature Request] 工具-杂项-自定义发送文本功能

### ISSUE THREAD

**Issue by blingbling22** [Hanxven/LeagueAkari#69]
- 发送文本功能可以多添加几个不同的文本，目前只有一个，所以我只能放 一个大拇指的图案，我想要嘲讽对手。
```
-----\▔\
-----)..)
-----/../▂▂▂
▂▂╱┈ ▕▂▂▂▏
▉┈-┈┈ ▕▂▂▂▏
▉┈-┈┈▕▂▂▂▏
▔▔╲▂▕▂▂
```
- 如果要发送全体，是不是要在每一行前面加 /all ，可否设置一个选项，发送该文本自动在前面加上 /all

**Comment by Hanxven** [comment]
1. 是否可以多添加几个不同的文本？

可以加入，但目前开发优先级靠后，可能要等到之后的版本。

2. 发送全体

由于该功能是模拟键盘，实际上可以按住 `shift` 键来添加 `/all` 前缀，就像使用 `shift` + `enter` 发送全体一样。

但目前可能有很多人不知道这种方法，未来可能会设计用 `ctrl` + `pageup` 这样的组合键来发送到全体。
