### ISSUE TITLE
[Feature Request]  能否跟随贴合客户端 

### ISSUE THREAD

**Issue by molover02** [Hanxven/LeagueAkari#71]
https://github.com/ping11700/LOLKit 类似这个项目一样
自己的窗体贴合客户端. 一起移动, 显示.
这样的话 就非常非常方便快捷.

**Comment by BakaFT** [comment]
1>需要考虑的边界条件太多。用户的分辨率，用户设置的客户端分辨率之类因素考虑起来麻烦得很
2>可能存在于其他东西的冲突，比如WeGame，或者PenguLoader，导致错位或显示异常
3>虽然开关可以解决2的问题，但是我只是想说付出大于汇报，我猜maintainer不会优先考虑，或者不会考虑这个功能

**Comment by Hanxven** [comment]
加入到考虑之中，但可能位于较低的开发优先级。

**Comment by molover02** [comment]
好耶, 在[Seraphine] 上提了相同的issue, 人家直接给close了....

https://github.com/ping11700/LOLKit  他的核心功能也太好用了,  大佬也考虑一下
还有这个项目的大佬也太厉害了, 项目体积还这么小, 咱们的能否也缩一下体积.

期待更新☺

**Comment by molover02** [comment]
https://github.com/molover02/LOL-tools GitHub上的lol工具基本都用了一下, 大家可以看看我写的感受😁😁😁,  蹭点经验

**Comment by Hanxven** [comment]
> 好耶, 在[Seraphine] 上提了相同的issue, 人家直接给close了....
> 
> https://github.com/ping11700/LOLKit 他的核心功能也太好用了, 大佬也考虑一下 还有这个项目的大佬也太厉害了, 项目体积还这么小, 咱们的能否也缩一下体积.
> 
> 期待更新☺

如果你了解 electron，你应该知道缩减体积是不可能的。
