### ISSUE TITLE
[Bug] 自动ban、pick均无效

### ISSUE THREAD

**Issue by anonymouscnuser** [Hanxven/LeagueAkari#73]
为了知道 BUG 的源头，请您尽可能描述：
自动ban、pick均无效
设置了各路的英雄，会自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick

1. 出现问题的版本。
1.2.3

3. 之前版本是否出现该问题？这将会帮助缩小排查范围。
否

5. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。
设置了各路的英雄，可以自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick

6. 这个问题具体是什么样子的？如果有截图或报错文字会更好。

7. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。
Win10 WeGame启动 火绒，应该没别的啥了

9. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。

感谢您的理解和配合。

**Comment by anonymouscnuser** [comment]
另外，1.2.2的包还有吗。发现产物里只有1.2.1和1.2.3

**Comment by Hanxven** [comment]
正在修复这个问题。

1.2.2 版本被误删除，现已重新上传到 Github Releases 中。

**Comment by 2018shawn** [comment]
> 为了知道 BUG 的源头，请您尽可能描述： 自动ban、pick均无效 设置了各路的英雄，会自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick
> 
> 1. 出现问题的版本。
>    1.2.3
> 2. 之前版本是否出现该问题？这将会帮助缩小排查范围。
>    否
> 3. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。
>    设置了各路的英雄，可以自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick
> 4. 这个问题具体是什么样子的？如果有截图或报错文字会更好。
> 5. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。
>    Win10 WeGame启动 火绒，应该没别的啥了
> 6. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。
> 
> 感谢您的理解和配合。

这个我的情况是刚开始不生效，后面设置选默认是有效的，然后取消默认 分路的设置也就有效了

**Comment by Hanxven** [comment]
> > 为了知道 BUG 的源头，请您尽可能描述： 自动ban、pick均无效 设置了各路的英雄，会自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick
> > 
> > 1. 出现问题的版本。
> >    1.2.3
> > 2. 之前版本是否出现该问题？这将会帮助缩小排查范围。
> >    否
> > 3. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。
> >    设置了各路的英雄，可以自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick
> > 4. 这个问题具体是什么样子的？如果有截图或报错文字会更好。
> > 5. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。
> >    Win10 WeGame启动 火绒，应该没别的啥了
> > 6. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。
> > 
> > 感谢您的理解和配合。
> 
> 这个我的情况是刚开始不生效，后面设置选默认是有效的，然后取消默认 分路的设置也就有效了

新版相关功能的设置存储忘记了考虑之前的结构，因此会出现和旧版本不相兼容的情况。在即将发布的更正版中将使用新的键。

**Comment by anonymouscnuser** [comment]
> > > 为了知道 BUG 的源头，请您尽可能描述： 自动ban、pick均无效 设置了各路的英雄，会自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick
> > > 
> > > 1. 出现问题的版本。
> > >    1.2.3
> > > 2. 之前版本是否出现该问题？这将会帮助缩小排查范围。
> > >    否
> > > 3. 如何复现这个问题？是在某些步骤下一定会复现，还是概率性复现？如果您不知道如何复现，也没有关系。
> > >    设置了各路的英雄，可以自动同意，但进去后不会自动亮英雄、也不会自动ban、也不会自动pick
> > > 4. 这个问题具体是什么样子的？如果有截图或报错文字会更好。
> > > 5. 系统平台的信息。Windows 10 or Windows 11？如果有一些特殊的系统设置或环境，也请点明。
> > >    Win10 WeGame启动 火绒，应该没别的啥了
> > > 6. 如果您也是开发者，可以提供更多专业细节，如控制台输出等。
> > > 
> > > 感谢您的理解和配合。
> > 
> > 
> > 这个我的情况是刚开始不生效，后面设置选默认是有效的，然后取消默认 分路的设置也就有效了
> 
> 新版相关功能的设置存储忘记了考虑之前的结构，因此会出现和旧版本不相兼容的情况。在即将发布的更正版中将使用新的键。

确实，我清空了数据。可以用了
