### ISSUE TITLE
希望增加功能：查看最近队友

### ISSUE THREAD

**Issue by opkhkh** [Hanxven/LeagueAkari#77]
![2024-07-31_113734](https://github.com/user-attachments/assets/116f9216-75eb-4ce0-b2d0-93cd3d776dbd)

**Comment by Hanxven** [comment]
已存在的功能。

**Comment by opkhkh** [comment]
有时候不显示近期队友名称

![2024-07-31_165522](https://github.com/user-attachments/assets/e20c905f-83ae-4e5d-a92f-d5b087726d11)
