### ISSUE TITLE
前几个版本可以选择只查看排位战绩,现在怎么好像找不到这个开关了?建议添加

### ISSUE THREAD

**Issue by yiyiow** [Hanxven/LeagueAkari#78]
灵感总是来自于四面八方，欢迎提出您的建议。但是在提出之前，请尽量遵守以下规则：

1. 是否已经有人提出过类似建议了？请先搜索一下。

2. 避免无意义客套话和无关修饰词句。

    **错误示范1**：作者辛苦了，希望能够增加一个新的 xxx 功能，谢谢。
    **错误示范2**：(●'◡'●)(❁´◡`❁)╰(*°▽°*)╯，希望能够增加一个新的 xxx 功能，阿里嘎多~~OvO。
    **正确示范**：希望增加一个新的功能，可以实现 xxx。

3. 避免提出宝宝需求。

    **错误示范1**：可以出一个解压教程吗？
    **错误示范2**：可以出一个使用教程吗？

4. 如果有现成的解决方案，可以提供链接或参考。

感谢您的理解和配合。

**Comment by opkhkh** [comment]
看看这是啥

![2024-08-01_142126](https://github.com/user-attachments/assets/3d897897-701b-4545-8fc7-827d8aa9a2e1)
