### ISSUE TITLE
[Feature Request] 是否能获取eol分值并展示？

### ISSUE THREAD

**Issue by CCint3** [Hanxven/LeagueAkari#79]
RT: 匹配、排位、大乱斗等

**Comment by Hanxven** [comment]
不能获取，并且目前也没有一个公认的计算方案。

P.S. WeGame 已移除 `teamElo` 字段。

引用 @BakaFT 的话：

> 很久以前，WeGame在获取战绩详情的接口里有一个字段teamElo，反映了这局游戏里团队的水平（从名字猜测），尽管如此，这个字段没有任何标注和解释，也没有任何在腾讯内部的人出来解释，只能当一个反应对局水平的模糊标准。最近几个月一直有人不断cue到这个东西，然后有一个公众号lz玉米先用这个做出了一个公众号产品，可以显示玩家的ELO分数，我猜大概是多把取平均？，还给出了一张段位和ELO分数对照的表格，我不好说。后来@极地iko发了个视频教人用Charles抓包查这个数据，也有很多人跟着发了不少教程，做了很多工具来简化这个流程，东西火了，所以腾讯就把这个字段从返回响应里去掉了。
这个分数只能打完看，并且排位系统会尽可能保证两个团队的teamElo接近，很难有什么参考价值，只能模糊地反映你的水平阶段（这是5个人地平均值）

> 这是在腾讯去掉这个字段之前发生的时间线，这个分数还算有说服力，毕竟是腾讯给的，只是不清楚算法细节罢了，尽管误差存在，但是多多少少勉强算个衡量标准。

> 在腾讯下手(7/12)之后，lz玉米的公众号短时间内也去掉了ELO分数显示，毕竟数据源都挂了。不过短短两三天之后，分数又回来了，并且@极地iko也在直播里开始“测试ELO分”，我简单挖了一下，背后靠的是一个叫 @小洛 的机器人，并且已经有一定的传播度，有部分主播已经在用（或者在有机器人的群里），至于这两者之间的关系，我不知道，但是他们似乎都找到了一种隐秘的方法获得数字。
既然腾讯已经不给数据了，那这些数字是怎么来的？我不知道。我知道的是：
1>@小洛的作者对算法只说了两个字，“保密”
2>每个人都可以写算法。我也可以写一个算法：直接从你的段位，根据之前lz玉米的表格反推一个基础分数，然后加上一点随机数即可；或者永远只返回2992（不过这个没人信）
3>我从WeGame、掌盟、LCUX、SGP抓包，没有看到一丁点相关的信息
3>我是秦始皇，在我的时代还没有算法，所以我不懂这些
