### ISSUE TITLE
设置保存在什么位置，更新版本后设置需要同步一下

### ISSUE THREAD

**Issue by cherryamme** [Hanxven/LeagueAkari#8]
设置保存在什么位置，更新版本后设置需要同步一下

**Comment by Hanxven** [comment]
由于改名后很多东西发生了变化，由于技术水平上的原因，暂时没办法将设置原封不动地搬过来。

可能要您手动同步了。

**Comment by cherryamme** [comment]
感觉可以搞个配置文件记录一下方便转移或同步。    
感谢，大乱斗玩家点确定和抢英雄很方便
---- Replied Message ----
| From | ***@***.***> |
| Date | 03/24/2024 20:44 |
| To | Hanxven/LeagueAkari ***@***.***> |
| Cc | cherryamme ***@***.***>,
Author ***@***.***> |
| Subject | Re: [Hanxven/LeagueAkari] 设置保存在什么位置，更新版本后设置需要同步一下 (Issue #8) |

由于改名后很多东西发生了变化，由于技术水平上的原因，暂时没办法将设置原封不动地搬过来。

可能要您手动同步了。

**Comment by Hanxven** [comment]
> 感觉可以搞个配置文件记录一下方便转移或同步。 感谢，大乱斗玩家点确定和抢英雄很方便 ---- Replied Message ---- | From | ***@***.***> | | Date | 03/24/2024 20:44 | | To | Hanxven/LeagueAkari ***@***.***> | | Cc | cherryamme ***@***.***>, Author ***@***.***> | | Subject | Re: [Hanxven/LeagueAkari] 设置保存在什么位置，更新版本后设置需要同步一下 (Issue #8) | 由于改名后很多东西发生了变化，由于技术水平上的原因，暂时没办法将设置原封不动地搬过来。 可能要您手动同步了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我会考虑在后面的版本使用更加通用一点的方式来记录设置。
