### ISSUE TITLE
[Bug] 部分玩家对局数据为空

### ISSUE THREAD

**Issue by opkhkh** [Hanxven/LeagueAkari#81]
![2024-08-08_224120](https://github.com/user-attachments/assets/38d58235-0e6b-42ce-8ace-6c4a2a4c1939)

有时候一场对局有两三个玩家不显示对局信息。
但是点击他们名称，查看他们战绩页面，匹配排位大乱斗数据都显示正常。

翻了下issues，跟这个有点像，不知是不是同一个问题。
https://github.com/Hanxven/LeagueAkari/issues/12#issue-2205841238

**Comment by Hanxven** [comment]
今日乱斗的时候也发现了，在调试日志中发现似乎是某个数据格式错误导致解析出错。

一个典型特征是：在出现如上空玩家时，无法再次操作该对局页面，表现为部分内容点击没反应，翻看控制台发现红色错误。

**Comment by Hanxven** [comment]
暂无法复现，重写了一部分逻辑，不知是否能解决。
