### ISSUE TITLE
[Feature Request] 请求添加黑名单和上局队友或对手功能

### ISSUE THREAD

**Issue by Swaynani** [Hanxven/LeagueAkari#86]
在峡谷中不免遇到骂人 开挂 送人头的队友 但是记不住ID 所以希望出一个功能 可以快速添加他到笔记本 下次对局遇到了 不管在自己队 还是对面 都心里有数应该怎么办了
还有一个就是可以出一个能看出这把的队友或者对手是不是上一把 或者之前遇到的人的功能

**Comment by BakaFT** [comment]
如果我没记错，均为已实现功能

**Comment by Swaynani** [comment]
> 如果我没记错，均为已实现功能

好的大佬 黑名单功能找到了 但是上局队友或者对手这个 真没找到

**Comment by Hanxven** [comment]
请另开 Issue。
