### ISSUE TITLE
[Feature Request] 希望添加游戏内类似wegame的快捷显示战绩功能和改变战绩排版

### ISSUE THREAD

**Issue by Swaynani** [Hanxven/LeagueAkari#88]
求一下游戏内按tab或者其他按键 按下显示战绩等信息 的功能 和 
目前的战绩显示排版观看起来不是很直观 也希望改一下

**Comment by Hanxven** [comment]
1. 游戏内 overlay: 游戏内叠加显示：难以做到
2. 战绩 layout: 巨大的工作量，闲下来会尝试。

**Comment by Swaynani** [comment]
> 1. 游戏内 overlay: 游戏内叠加显示：难以做到
> 2. 战绩 layout: 巨大的工作量，闲下来会尝试。

好的 辛苦大佬

**Comment by Hanxven** [comment]
#91
