### ISSUE TITLE
能否实现在多开客户端的情况下切换使用

### ISSUE THREAD

**Issue by longyi995661393** [Hanxven/LeagueAkari#9]
首先描述我自身的使用情况：
日常多开两个客户端，软件只会识别到第一个登录的账号使用
例如我第一个登录的是A号，第二个登录的是B号
软件只会识别到A号
并且一切功能以A号为主

这个时候我如果想要软件识别到B号的话
这个时候就得关闭软件和两个客户端
然后第一个去登录B号 第二个去登录A号
这样软件就识别到了B号

我希望能够在不退出两个LOL客户端的情况下
让软件可以在多开客户端的情况下去切换任意一个LOL客户端使用

**Comment by Hanxven** [comment]
我理解你的需求，这个应该不难实现。请等待日后的更新。

如果功能实现，我会在此 issue 下通知。

**Comment by longyi995661393** [comment]
感谢 期待您的更新！

**Comment by Hanxven** [comment]
已并入到更新中。[1.1.4](https://github.com/Hanxven/LeagueAkari/releases/tag/1.1.4)

**Comment by longyi995661393** [comment]
首先感谢您的更新，目前已下载新版在使用了
关于多客户端有两个地方希望可以优化一下
具体我已经录制的视频中，希望您予以采纳
链接：https://pan.baidu.com/s/1vqjcjKLLag-QZZ09WODz5Q 
提取码：1234

**Comment by Hanxven** [comment]
如果可以，请尽量发送 Markdown 格式的图文内容。

关于：

## 1. 客户端信息问题

展示的信息是在未连接时能通过命令行获取到的最多信息了，我没有办法在不连接的状态下获取登录账号或召唤师名等内容。

## 2. 切换问题

这个可以考虑实现，需要改的地方有点多。

---

多客户端并不是非常普遍的使用用例，因此在此需求之上的开发可能会暂缓。
