### ISSUE TITLE
[Feature Request] 建议调整对局页面排版

### ISSUE THREAD

**Issue by opkhkh** [Hanxven/LeagueAkari#91]
对于5v5对局（匹配排位大乱斗），采用左右两列排版或者上下两行排版

一边为己方，另一边为敌方
或者一边为蓝方，另一边为红方

对于排位，根据位置分配由上到下排序，或从左到右排序

**Comment by Hanxven** [comment]
将尝试按照 Seraphine 的布局重构。

**Comment by Hanxven** [comment]
已尝试应用新布局，将在下个版本 (v1.2.5) 调整。
