### ISSUE TITLE
[Feature Request] 标记玩家功能是否可以保存在本地？

### ISSUE THREAD

**Issue by Swaynani** [Hanxven/LeagueAkari#92]
今天由于电脑问题 重装了系统 后发现软件之前标记的所有玩家都失效了 包括所有设置 以及大乱斗设置英雄 软件是没有安装在C盘的

**Comment by BakaFT** [comment]
正因为这些东西**保存在本地**，才会因为你的**重装**操作所抹除

不过这里的本地是相对于**远程服务器**来说的，配置确实存在了本地，但是正好存在了你格式化的地方：`C:\Users\{用户名}\AppData\Roaming\league-akari`

这是一个约定好的地方，我相信有很多软件都会丢失配置，Akari当然也不会例外，我认为这是**符合预期**的行为

请注意**自行备份**

**Comment by Swaynani** [comment]
> 正因为这些东西**保存在本地**，才会因为你的**重装**操作所抹除
> 
> 不过这里的本地是相对于**远程服务器**来说的，配置确实存在了本地，但是正好存在了你格式化的地方：`C:\Users\{用户名}\AppData\Roaming\league-akari`
> 
> 这是一个约定好的地方，我相信有很多软件都会丢失配置，Akari当然也不会例外，我认为这是**符合预期**的行为
> 
> 请注意**自行备份**

好的 感谢 下次重启或者清除数据的时候我把这个目录保存下来之后替换就可以了..
