### ISSUE TITLE
[Feature Request] 玩家标记功能是否可以全局通用?

### ISSUE THREAD

**Issue by Swaynani** [Hanxven/LeagueAkari#94]
有些人外服一个区的账号很多，在台服A账号标记的玩家，当我玩台服B账号的时候也可以显示台服A账户是标记的玩家？这个功能很有用，真的希望可以实现

**Comment by Hanxven** [comment]
目前的数据是特地通过账号和大区分了类，看起来造成了不必要问题。将提供一个选项，同大区的标记将共享到所有账户中，并注明标记账户。
