### ISSUE TITLE
[Bug] 最后一秒秒退，有概率出现时间上的错误

### ISSUE THREAD

**Issue by zhangzw218** [Hanxven/LeagueAkari#95]
![image](https://github.com/user-attachments/assets/4fb6a853-8a66-4aad-b33e-87ca87afbf1f)

出现的规律，我也搞不清，有时候开启，时间就是错误的，这时候，如果关掉重开，又有概率会正常
如果原本时正常的，多次开关之后，也有可能出错。
总之，只要切换几次开关，问题应该能重现

**Comment by Hanxven** [comment]
已知问题。不过时间是根据 gameflow session 的部分字段获取，暂无法知道其他的同步方式。

**Comment by Hanxven** [comment]
添加了一个设置方式，大概能缓解此现象。

**Comment by zhangzw218** [comment]
> 添加了一个设置方式，大概能缓解此现象。
我现在的实践是，开启最后一秒秒退之后，切换一下角色，这时候时间会刷新，时间就是准确的。
