### ISSUE TITLE
[Feature Request] 在辅助窗口添加技能CD对比

### ISSUE THREAD

**Issue by jin7570** [Hanxven/LeagueAkari#96]
希望可以在辅助窗口添加一个技能介绍以及技能cd比对功能（包括召唤师技能），可以在双方选择完英雄后自动选择对位英雄（默认自动，可以手动修改对位英雄）或者是游戏加载时（这个时候应该必可以拿到对方的阵容了吧），然后显示对位英雄的各种技能介绍，以及跟自己的英雄对比技能cd之类的。

**Comment by Hanxven** [comment]
似乎很难做。

**Comment by Hanxven** [comment]
暂无实现打算。
