### ISSUE TITLE
[Feature Request] 是否可以添加敌方英雄消失以及出现的提示

### ISSUE THREAD

**Issue by vahallaaa** [Hanxven/LeagueAkari#99]
![image](https://github.com/user-attachments/assets/6b53d08b-8494-4462-b11e-0d9b25c03339)
需求是峡谷中敌方的miss队友有时会不及时报告,以及大乱斗中妮蔻变身隐藏在兵线中,但是可以通过Tab中根据视野反馈头像亮起来分辨
想知道,类似于软件已有的重生倒计时功能是算在游戏内还是客户端呢,是否有读内存
按下Tab计分面板显示的敌方英雄消失在视野中头像会变灰,在视野内则完整显示,这样的游戏内指令能否通过某种方式获取到
请指教谢谢

**Comment by Hanxven** [comment]
该功能无法实现。
